README.md, src/AssetsTransferApi.ts, src/createXcmTypes/RelayToPara.spec.ts, src/createXcmTypes/RelayToPara.ts, src/createXcmTypes/SystemToPara.spec.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToRelay.spec.ts, src/createXcmTypes/SystemToRelay.ts
=> Add SystemToRelay V2 and V3

src/createXcmTypes/RelayToPara.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToRelay.ts, src/createXcmTypes/types.ts
closes https://github.com/paritytech/asset-transfer-api/issues/101
=> Change paraId to destId for createDest

.npmignore
closes: https://github.com/paritytech/asset-transfer-api/issues/108
=> Fix npm ignore for lib and build

src/AssetsTransferApi.ts, src/registry/parseRegistry.spec.ts, src/registry/parseRegistry.ts, src/registry/types.ts
rel: https://github.com/paritytech/asset-transfer-api/issues/112
=> Add registry to AssetsTransferApi

src/AssetsTransferApi.ts, src/registry/findRelayChain.spec.ts, src/registry/findRelayChain.ts
closes: https://github.com/paritytech/asset-transfer-api/issues/112
=> Add findRelayChain for a given specName

scripts/createRegistry.ts, src/AssetsTransferApi.spec.ts, src/registry/parseRegistry.spec.ts, src/registry/registry.json, src/registry/types.ts
* update create registry script to include Statemint and Statemine asset ids in registry
=> Add System Parachain Asset Ids

src/AssetsTransferApi.spec.ts, src/AssetsTransferApi.ts, src/createXcmCalls/index.ts, src/createXcmCalls/limitedReserveTransferAssets.spec.ts, src/createXcmCalls/limitedReserveTransferAssets.ts, src/createXcmCalls/limitedTeleportAssets.spec.ts, src/createXcmCalls/limitedTeleportAssets.ts, src/createXcmCalls/reserveTransferAssets.spec.ts, src/createXcmCalls/reserveTransferAssets.ts, src/createXcmCalls/teleportAssets.spec.ts, src/createXcmCalls/teleportAssets.ts, src/createXcmTypes/RelayToPara.spec.ts, src/createXcmTypes/RelayToPara.ts, src/createXcmTypes/RelayToSystem.spec.ts, src/createXcmTypes/RelayToSystem.ts, src/createXcmTypes/SystemToPara.spec.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToRelay.spec.ts, src/createXcmTypes/SystemToRelay.ts, src/createXcmTypes/types.ts, src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts, src/registry/findRelayChain.ts, src/registry/index.ts, src/registry/types.ts, src/types.ts
Waiting on https://github.com/paritytech/asset-transfer-api/issues/136 to be resolved for `SystemToPara` but I will continue to work on the rest of the logic.
=> Add teleport logic to AssetsTransferApi

README.md
closes: https://github.com/paritytech/asset-transfer-api/issues/116
=> Update readme with more docs

src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/util/checkIsAscendingOrder.ts, src/createXcmTypes/util/dedupeMultiAssets.spec.ts, src/createXcmTypes/util/dedupeMultiAssets.ts, src/createXcmTypes/util/sortMultiAssetsAscending.ts, src/types.ts
* removes duplicate values from a sorted list of multiassets
* dedupe unit tests
closes: [#154](https://github.com/paritytech/asset-transfer-api/issues/154)
=> ensure multi assets deduped

src/createXcmCalls/limitedTeleportAssets.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/util/getTokenSymbolGeneralIndex.spec.ts, src/createXcmTypes/util/getTokenSymbolGeneralIndex.ts
* adds a function to get the general index of a token symbol on a system chain
* closes [#174](https://github.com/paritytech/asset-transfer-api/issues/174)
=> add function to get general index of valid token symbol

src/AssetsTransferApi.ts, src/createXcmTypes/index.ts, src/types.ts
closes: https://github.com/paritytech/asset-transfer-api/issues/164
=> Add ParaToSystem not supported

package.json, yarn.lock
Update the following deps:
"@polkadot/api": "^10.9.1"
=> chore(deps): update polkadot-js

examples/relayToPara.ts, examples/relayToSystem.ts, examples/submittable.ts, examples/systemToPara.ts, examples/systemToRelay.ts
rel: https://github.com/paritytech/asset-transfer-api/issues/165
This adds an example for `SubmittableExtrinsics`
=> Add submittable example

src/AssetsTransferApi.ts, src/createXcmTypes/SystemToPara.ts, src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts
This focuses on cleaning up some technical debt.
- Cleanup an import
- Cleanup `createXcmTxInput`
=> chore: cleanup tech debt

.github/workflows/semantic.yml
Ensure the title is in line with conventional commits
=> ci: semantic title check

scripts/testNetworkLiquidAssets.ts, src/AssetTransferApi.ts
Remove `createType('Call')` where applicable, and add a eslint disable in the scripts
=> fix(internal): remove createType(Call) where applicable

src/createXcmTypes/ParaToPara.ts, src/createXcmTypes/ParaToSystem.ts, src/createXcmTypes/RelayToPara.ts, src/createXcmTypes/RelayToSystem.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToRelay.ts, src/createXcmTypes/SystemToSystem.ts
This adjusts the inline docs to be more accurate with the exposed modules.
=> docs: adjust inline docs for `createXcmTypes`

RELEASE.md
Documentation for releasing to NPM and github.
=> docs: add `RELEASE.md`

package.json, src/testHelpers/adjustedMockSystemApiV1004000.ts, src/testHelpers/adjustedMockSystemApiV1007000.ts, yarn.lock
NOTE: This also ensure there is no `^` on the PJS versions to ensure it doesn't automatically update the patch version.
=> chore(deps): up pjs

e2e-tests/__snapshots__/hydration.ethereum.spec.ts.snap, e2e-tests/__snapshots__/moonbeam.hydration.spec.ts.snap, e2e-tests/__snapshots__/polkadotAssetHub.bridgeHub.spec.ts.snap, e2e-tests/__snapshots__/polkadotAssetHub.hydration.spec.ts.snap, e2e-tests/hydration.ethereum.spec.ts, e2e-tests/moonbeam.hydration.spec.ts, e2e-tests/polkadotAssetHub.bridgeHub.spec.ts, e2e-tests/polkadotAssetHub.hydration.spec.ts
* changed balance rounding precision from 3 to 2
* increased timeouts to improve snapshot test consistency
=> test: update e2e tests

src/createXcmTypes/util/createXcmVersionedAssetId.ts, src/createXcmTypes/util/getParachainNativeAssetLocation.ts, src/util/resolveMultiLocation.ts
Rel: https://github.com/paritytech/asset-transfer-api/issues/539
=> fix: add type guards to fix error from getDestinationXcmWeightToFeeAsset

.gitignore, package.json, src/registry/Registry.ts, src/registry/registry-json-cjs.cts, src/registry/registry-json.ts, yarn.lock
See https://github.com/paritytech/asset-transfer-api/pull/561#pullrequestreview-2848336435
=> chore: use tshy

examples/getDestinationXcmWeightToFeeAsset.ts
Taken from https://github.com/paritytech/asset-transfer-api/pull/519
=> feat: Add example for getDestinationXcmWeightToFeeAsset
