paritytech/asset-transfer-api

src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts
* adds check to ensure integer asset id inputs exist on each respective system parachain
* adds  test for system to para
* adds test for para to para
closes [#128](https://github.com/paritytech/asset-transfer-api/issues/128)
=> check integer asset ids are valid system

src/AssetsTransferApi.spec.ts, src/createXcmTypes/SystemToPara.ts
This ensures when we create xcm types for assets for `SystemToPara` we correctly input the right `parents` value depending on the token.
=> Fix parents for native vs non-native tokens when construct xcm types for assets

package.json, src/AssetsTransferApi.spec.ts, src/consts.ts, src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts, src/registry/parseRegistry.spec.ts, src/registry/types.ts, yarn.lock
* changes input validation logic to be based on xcm direction for RelayToSystem, RelayToPara, SystemToRelay and SystemToPara directions
* closes [#138](https://github.com/paritytech/asset-transfer-api/issues/138)
=> make xcm input validation direction based

scripts/testNetworkSetup.ts
rel: https://github.com/paritytech/asset-transfer-api/issues/106
This doesn't fix the overall issue with the V3 Barrier Trait Error but sets the script to use V3.
=> Update testnetwork script to use V3 for asset creation

src/createXcmTypes/RelayToPara.spec.ts, src/createXcmTypes/RelayToPara.ts, src/createXcmTypes/SystemToPara.spec.ts, src/createXcmTypes/SystemToPara.ts, src/validate/validateAddress.spec.ts, src/validate/validateAddress.ts
closes: https://github.com/paritytech/asset-transfer-api/issues/43
This adds support for ethereum addresses. It only really matters for `SystemToPara`, and `RelayToPara` so we added it to those directions.
=> Add support for AccountKey20

src/AssetsTransferApi.ts, src/createXcmTypes/RelayToPara.spec.ts, src/createXcmTypes/RelayToSystem.spec.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToRelay.spec.ts, src/createXcmTypes/types.ts, src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts, src/integrationTests/AssetsTransferApi.spec.ts
Ensure `SystemToRelay` is a teleport.
Reorganize xcmDirection validation checks.
=> Add additional xcmDirection validation checks, fix SystemToRelay AssetType

src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts
closes: https://github.com/paritytech/asset-transfer-api/issues/168
=> Ensure a user can input a native token or have an empty array for tx's to or from relay

.github/workflows/pr.yml
GitHub is going to deprecate `save-state` and `set-output` commands. [More info](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
This PR adjusts GHA workflow to use new syntax.
Part of https://github.com/paritytech/ci_cd/issues/805
=> fix set-output (upcoming deprecation) in GHA 

src/AssetsTransferApi.spec.ts, src/AssetsTransferApi.ts, src/createXcmTypes/types.ts, src/errors/checkLocalTxInputs.spec.ts, src/errors/checkLocalTxInputs.ts, src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts, src/registry/Registry.spec.ts, src/registry/Registry.ts, src/registry/index.ts, src/registry/types.ts, src/types.ts
I reworked the registry to save on performance, and memory while also exposing a bunch of public functions to the user. 
```typescript
// Getter for the complete registry
public get getRegistry
// Getter for the name of the relay chain for this network
public get getRelayChain
// Getter for the registry associated with this networks relay chain
public get getRelaysRegistry
// Lookup all chains that have the following token symbol. It will return an array
// with all the chains that have the following token symbols. Note this will only
// be searched in the respective relay chains registry.
public lookupTokenSymbol(symbol: string)
// Lookup all chains that have the following assetId. It will return an array
// with all the chains that have the following AssetId. Note this will only
// be …
```
=> Rework the Registry to be a public class

src/AssetsTransferApi.ts, src/createXcmCalls/limitedReserveTransferAssets.spec.ts, src/createXcmCalls/limitedReserveTransferAssets.ts, src/createXcmCalls/limitedTeleportAssets.spec.ts, src/createXcmCalls/limitedTeleportAssets.ts, src/createXcmCalls/reserveTransferAssets.spec.ts, src/createXcmCalls/reserveTransferAssets.ts, src/createXcmCalls/teleportAssets.spec.ts, src/createXcmCalls/teleportAssets.ts, src/createXcmTypes/RelayToPara.spec.ts, src/createXcmTypes/RelayToSystem.spec.ts, src/createXcmTypes/SystemToPara.spec.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToRelay.spec.ts, src/createXcmTypes/types.ts
This rethreads the `registry` as an `opt` down to `SystemToPara` in order to avoid calling `parseRegistry`.
The layers of threading are:
`AssetTransferApi` -> `extrinsic call` -> `createXcmTypes`
=> Rethread Registry down to createAssets, and createFeeAssetItem as an option

examples/colors.ts, examples/relayToPara.ts, examples/relayToSystem.ts, examples/submittable.ts, examples/systemToPara.ts, examples/systemToRelay.ts
rel: https://github.com/paritytech/asset-transfer-api/issues/165
This adds coloring, and decoding examples to all xcmDirections and the submittable example
=> Update all examples with decoding and colors

scripts/testNetworkSetup.ts
I modified the XCM Message to start with `unpaidExecution` so that it passes the barrier specified by `xcm_config.rs` on Polkadot and Kusama. Solves issue #106 .
=> fix: added unpaidExecution for testnet XCM message

src/AssetsTransferApi.spec.ts, src/AssetsTransferApi.ts, src/consts.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToSystem.ts, src/createXcmTypes/util/isSystemChain.spec.ts, src/createXcmTypes/util/isSystemChain.ts, src/errors/checkXcmTxInputs.ts
* removed SYSTEM_PARACHAINS_IDS
* checks if a chainId is a system chain based on whether its ID is strictly less than 2000 and greater than 0
closes: [#218](https://github.com/paritytech/asset-transfer-api/issues/218)
=> Update System Parachain Id check based on chainId

README.md
closes: [#245](https://github.com/paritytech/asset-transfer-api/issues/245)
=> Fix: remove incorrect reference to '0' for Native Relay Token

src/createXcmTypes/util/foreignAssetsMultiLocationExists.spec.ts, src/createXcmTypes/util/foreignAssetsMultiLocationExists.ts, src/createXcmTypes/util/getAssetHubAssetId.spec.ts, src/createXcmTypes/util/getAssetHubAssetId.ts, src/errors/checkLocalTxInputs.ts, src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts
* re-adds `foreignAssetsMultiLocationExists` for checking AssetHub chain state if a foreign asset isn't found in the registry
=> Re-implement AssetHub ForeignAsset queries

src/createXcmTypes/SystemToRelay.ts
This resolves a TODO that has to do with an unnecessary passing down of `destId` for SystemToRelay.
=> fix: resolve TODO for destId for relay chains

src/errors/checkLocalTxInputs.spec.ts, src/errors/checkLocalTxInputs.ts
* fixes an issue where an empty string assetId returns the `Assets` tx type for local txs instead of `Balances`
=> fix empty string assetId Balances bug for local tx

src/AssetsTransferApi.ts, src/consts.ts, src/createXcmTypes/ParaToSystem.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToSystem.ts, src/createXcmTypes/util/getAssetId.ts, src/createXcmTypes/util/sortMultiAssetsAscending.ts, src/errors/checkXcmTxInputs.ts, src/testHelpers/adjustedMockSystemApi.ts, src/types.ts, src/validate/index.ts, src/validate/validateNumber.spec.ts, src/validate/validateNumber.ts
closes: https://github.com/paritytech/asset-transfer-api/issues/263
This replaces all instances where a MAX_INTEGER_OVERFLOW can happen.
=> fix: replace all unsafe instances of parseInt

examples/systemToParaLpToken.ts, src/AssetsTransferApi.spec.ts, src/createXcmTypes/ParaToSystem.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToSystem.ts, src/createXcmTypes/util/fetchPalletInstanceId.spec.ts, src/createXcmTypes/util/fetchPalletInstanceId.ts, src/createXcmTypes/util/foreignAssetsMultiLocationExists.spec.ts, src/errors/checkXcmTxInputs.spec.ts, src/registry/Registry.ts, src/registry/parseRegistry.spec.ts, src/registry/types.ts
rel: https://github.com/paritytech/asset-transfer-api/issues/268
This PR focuses on giving support for `ForeignAssets` inside of `fetchPalletInstanceId` so we can remove `foreignAssetsPalletInstance` from the registry.
=> fix: adjust `fetchPalletInstanceId` to handle `ForeignAssets` pallet

src/AssetsTransferApi.ts, src/config/disabledOpts.ts, src/errors/BaseError.ts, src/errors/checkBaseInputOptions.spec.ts, src/errors/checkBaseInputOptions.ts, src/errors/disableOpts.spec.ts, src/errors/disableOpts.ts
This ensures and allows us to add disabling for certain options regarding the `createTransferTransaction` function ie `TransferArgsOpts<T extends Format>`. All one needs to do is going into `config/disabledOpts` and switch the `disabled` key to true, and add which chains are disabled in the `chains` field. 
NOTE: for the `chains` field if we need to disable it for all chains just add `*`.
=> feat: add disabled options config and function

src/AssetsTransferApi.ts, src/createXcmTypes/ParaToSystem.ts, src/createXcmTypes/util/getAssetId.ts, src/createXcmTypes/util/isSystemChain.spec.ts, src/createXcmTypes/util/isSystemChain.ts, src/errors/checkXcmTxInputs.ts, src/util/getFeeAssetItemIndex.ts
This removes all the remaining instances of `parseInt`. It also chains the input of `isSystemChain` to only take in strings for `chainId`.
=> fix: remove remaining use of `parseInt`

src/AssetTransferApi.ts, src/createCalls/foreignAssets/transfer.spec.ts, src/createCalls/foreignAssets/transfer.ts, src/createCalls/foreignAssets/transferKeepAlive.spec.ts, src/createCalls/foreignAssets/transferKeepAlive.ts, src/createXcmTypes/ParaToSystem.ts, src/createXcmTypes/SystemToPara.spec.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToSystem.ts, src/createXcmTypes/util/constructForeignAssetMultiLocationFromAssetId.spec.ts, src/createXcmTypes/util/constructForeignAssetMultiLocationFromAssetId.ts, src/createXcmTypes/util/dedupeMultiAssets.spec.ts, src/createXcmTypes/util/dedupeMultiAssets.ts, src/createXcmTypes/util/sortMultiAssetsAscending.spec.ts, src/createXcmTypes/util/sortMultiAssetsAscending.ts, src/types.ts, src/util/getFeeAssetItemIndex.spec.ts, src/util/getFeeAssetItemIndex.ts, src/util/resolveMultiLocation.spec.ts, src/util/resolveMultiLocation.ts
This removes all uses of `MultiLocation`, and replaces it with its correct versioned type.
This also removes all `InteriorMultiLocation` types.
This also fixes up some loose types and makes them more strict.
=> fix: remove all use of `MultiLocation`, and use correct versioned type.

examples/rococoAssetHubToRelay.ts, src/consts.ts, src/registry/Registry.spec.ts, src/registry/findRelayChain.ts, src/registry/parseRegistry.spec.ts, src/registry/parseRegistry.ts
rel: https://github.com/paritytech/asset-transfer-api/pull/293
This ensures that the registry can initialize with rococo as the relay chain.
In order to use rococo's asset hub with the `AssetTransferApi` one will need to hardcode the `specName` into the initialization like the following:
```typescript
new AssetTransferApi(api, `asset-hub-rococo`, xcmVersion);
```
The reason being, kusama's asset hub and and rococo's asset-hub both share the same specName currently and will cause conflicts. We currently do an overewrite in the registry that the api uses and set the `specName` for rococo's asset hub to be `asset-hub-rococo`. This should be resolved at a higher level in the below PR for asset-hub's spec.
rel: https://github.com/paritytech/polkadot-sdk/pull/1215
=> fix: rococo initialization in the registry

src/createXcmCalls/polkadotXcm/limitedReserveTransferAssets.ts, src/createXcmCalls/polkadotXcm/limitedTeleportAssets.ts, src/createXcmCalls/polkadotXcm/reserveTransferAssets.ts, src/createXcmCalls/polkadotXcm/teleportAssets.ts, src/createXcmTypes/ParaToPara.spec.ts, src/createXcmTypes/ParaToPara.ts, src/createXcmTypes/ParaToSystem.spec.ts, src/createXcmTypes/ParaToSystem.ts, src/createXcmTypes/RelayToPara.spec.ts, src/createXcmTypes/RelayToPara.ts, src/createXcmTypes/RelayToSystem.spec.ts, src/createXcmTypes/RelayToSystem.ts, src/createXcmTypes/SystemToPara.spec.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToRelay.spec.ts, src/createXcmTypes/SystemToRelay.ts, src/createXcmTypes/SystemToSystem.spec.ts, src/createXcmTypes/SystemToSystem.ts, src/createXcmTypes/types.ts
rel: https://github.com/paritytech/asset-transfer-api/issues/301
part 1.
This ensures we don't rely on `createType` for type generation, and focuses first on refactoring destination and beneficiary type generators to ensure PR's stay small.
=> fix(internal): refactor dest and beneficiary types generators

src/constructApiPromise.ts, src/createXcmCalls/polkadotXcm/limitedReserveTransferAssets.ts, src/createXcmCalls/polkadotXcm/limitedTeleportAssets.ts, src/createXcmCalls/polkadotXcm/reserveTransferAssets.ts, src/createXcmCalls/polkadotXcm/teleportAssets.ts, src/createXcmCalls/util/fetchSafeXcmVersion.spec.ts, src/createXcmCalls/util/fetchSafeXcmVersion.ts, src/createXcmCalls/xTokens/transferMultiAsset.ts, src/createXcmCalls/xTokens/transferMultiAssetWithFee.ts, src/createXcmCalls/xTokens/transferMultiAssets.ts, src/createXcmTypes/ParaToPara.spec.ts, src/createXcmTypes/ParaToPara.ts, src/createXcmTypes/ParaToSystem.spec.ts, src/createXcmTypes/ParaToSystem.ts, src/createXcmTypes/RelayToPara.spec.ts, src/createXcmTypes/RelayToPara.ts, src/createXcmTypes/RelayToSystem.spec.ts, src/createXcmTypes/RelayToSystem.ts, src/createXcmTypes/SystemToPara.spec.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToRelay.spec.ts, src/createXcmTypes/SystemToRelay.ts, src/createXcmTypes/SystemToSystem.spec.ts, src/createXcmTypes/SystemToSystem.ts, src/createXcmTypes/types.ts
- Refactor all `createWeightLimit` calls to be return `XcmWeight` types instead of Polkadot-js weight types.
- Refactor all `createFeeAssetItem` calls to return a `number` type instead of a `u32` polkadot-js type.
rel: https://github.com/paritytech/asset-transfer-api/issues/301
=> fix(internal): refactor all weight limits to not use createType

package.json, scripts/testNetworkLiquidAssets.ts
Two questions I have regarding this:
* Currently I have to force pjs to accept `<any>` when dealing with the `asset-conversion-pallet`, because the types it expects come from the `substrate-node` implementation and are incompatible with the `Kusama Asset Hub` implementation, but due to this I have to disable `eslint` for those two lines.
```typescript
const createLiquidityPoolCall = (api: ApiPromise) => {
// For now, we have to override the types of the Assets until PJS is updated
// eslint-disable-next-line @typescript-eslint/no-unsafe-argument
return api.tx.assetConversion.createPool(<any>native, <any>asset);
};
const addLiquidityCall = (api: ApiPromise, amountNative: number, amountAsset: number, to: KeyringPair) => {
// For now, we have to override the types of the Assets until PJS is …
```
=> test: add liquid assets script to test network

jest.config.js
Since the refactor of the createTypes, I had fixed the examples `build` for tsconfig, which caused the tests to run twice. This PR ensures that the `/build` folder is ignored for tests.
=> test: fix jest tests running twice

src/AssetTransferApi.ts, src/createXcmCalls/util/establishXcmPallet.ts, src/createXcmTypes/util/getAssetId.ts, src/errors/checkXcmTxInputs.ts
This ensures we check and supply the right naming of `xTokens` pallet depending on the chain we are dealing with.
=> fix: xtokens and xTokens naming

src/AssetTransferApi.ts, src/createXcmCalls/polkadotXcm/limitedReserveTransferAssets.spec.ts, src/createXcmCalls/polkadotXcm/limitedReserveTransferAssets.ts, src/createXcmCalls/polkadotXcm/limitedTeleportAssets.spec.ts, src/createXcmCalls/polkadotXcm/limitedTeleportAssets.ts, src/createXcmCalls/polkadotXcm/reserveTransferAssets.spec.ts, src/createXcmCalls/polkadotXcm/reserveTransferAssets.ts, src/createXcmCalls/polkadotXcm/teleportAssets.spec.ts, src/createXcmCalls/polkadotXcm/teleportAssets.ts, src/createXcmCalls/polkadotXcm/types.ts, src/createXcmCalls/xTokens/transferMultiAsset.spec.ts, src/createXcmCalls/xTokens/transferMultiAssetWithFee.spec.ts, src/createXcmCalls/xTokens/transferMultiAssets.spec.ts, src/createXcmCalls/xTokens/transferMultiasset.ts, src/createXcmCalls/xTokens/transferMultiassetWithFee.ts, src/createXcmCalls/xTokens/transferMultiassets.ts, src/createXcmCalls/xTokens/types.ts, src/createXcmTypes/types.ts, src/errors/checkXcmTxInputs.ts, src/errors/types.ts, src/types.ts
[Tech debt]!
This cleans up the calls for `Xtokens`, and `polkadotXcm` to be cleaner and more understandable. This is part of an effort to decrease the size of args passed into calls.
This also extends `BaseArgs` to `checkXcmTxInputs`
=> fix(internal): cleanup structure for args passed into calls

tsconfig.json
This ensures spec files are not included in the build.
=> build: remove .spec files from lib

src/createXcmTypes/ParaToPara.spec.ts, src/createXcmTypes/ParaToSystem.spec.ts, src/createXcmTypes/SystemToSystem.spec.ts, src/util/resolveMultiLocation.spec.ts, src/util/sanitizeKeys.spec.ts, src/util/sanitizeKeys.ts, src/validate/validateNumber.ts
Ensure all values within `sanitizeKeys` are sanitized to strings if the value is a int. This specifically affects anything that uses `resolveMultilocation`, and `sanitizeKeys`.
This is especially effective since values that are recieved in the registry, the chain, or polkadot-js may not be 100% guaranteed to have the same structure we may expect.
closes: https://github.com/paritytech/asset-transfer-api/issues/345
=> fix(internal): ensure all `sanitizeKeys` int values are sanitized to str

zombienet/medium-network.toml, zombienet/small-network.toml
I get the error
```
Error: Input("Error opening spec file `statemine-local`: No such file or directory (os error 2)")
```
when I try to run `zombienet` with the toml file of small/medium network.
I renamed `statemine` to `asset-hub-rococo` in the toml files of zombienet.
=> fix: renaming statemine in zombienet toml files

src/AssetTransferApi.spec.ts, src/AssetTransferApi.ts, src/createXcmTypes/util/getAssetId.spec.ts, src/createXcmTypes/util/getAssetId.ts, src/createXcmTypes/util/getXcAssetMultiLocationByAssetId.spec.ts, src/errors/checkLocalTxInput/checkLocalTxInput.spec.ts, src/errors/checkXcmTxInputs.spec.ts, src/util/getFeeAssetItemIndex.spec.ts
This is a small PR that just removes the `_` from internal naming.
=> fix(internal-refactor): adjust naming to be more conventional

src/AssetTransferApi.ts, src/util/deepEqual.spec.ts, src/util/deepEqual.ts
closes: https://github.com/paritytech/asset-transfer-api/issues/364
This ensures when we compare two LP tokens that we do a deep equal comparison.
=> fix(internal): add deepEqual functionality for comparing two objects

src/AssetTransferApi.spec.ts, src/createXcmTypes/util/getAssetId.spec.ts, src/createXcmTypes/util/getXcAssetMultiLocationByAssetId.spec.ts, src/errors/checkLocalTxInput/checkLocalTxInput.spec.ts, src/errors/checkXcmTxInputs.spec.ts, src/integrationTests/AssetsTransferApi.spec.ts, src/integrationTests/parachains/bifrost.spec.ts, src/integrationTests/parachains/moonriver.spec.ts, src/util/getFeeAssetItemIndex.spec.ts
This ensures that any instantiation of `AssetTransferApi` uses the `NPM` registry instead of the CDN so that tests can run in an offline enviornment.
=> test: set registries to NPM for AssetTransferApi

src/AssetTransferApi.spec.ts, src/AssetTransferApi.ts, src/integrationTests/AssetsTransferApi.spec.ts, src/testHelpers/adjustedMockSystemApiV1004000.ts
This PR contains changes to `checkAssetLpTokenPairExists` which now gets the json representation of queried LP token asset locations for creating location types instead of using string derived values which caused issues destructuring some asset locations when using the `paysWithFeeOrigin` option.
closes: [#389](https://github.com/paritytech/asset-transfer-api/issues/389)
=> fix: update lp pool token storage key destructuring

src/AssetTransferApi.ts, src/consts.ts, src/createXcmTypes/SystemToBridge.ts, src/createXcmTypes/SystemToPara.ts, src/createXcmTypes/SystemToSystem.ts, src/createXcmTypes/util/assetIdsContainsRelayAsset.ts, src/createXcmTypes/util/createAssetLocations.ts, src/createXcmTypes/util/getAssetId.spec.ts, src/createXcmTypes/util/getAssetId.ts, src/createXcmTypes/util/isRelayNativeAsset.spec.ts, src/createXcmTypes/util/isRelayNativeAsset.ts, src/errors/checkBaseInputTypes.spec.ts, src/errors/checkBaseInputTypes.ts, src/errors/checkLocalTxInput/checkLocalRelayInput.spec.ts, src/errors/checkLocalTxInput/checkLocalRelayInput.ts, src/errors/checkLocalTxInput/checkLocalTxInput.spec.ts, src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts
This PR improves error messaging which previously only mentioned integer assetIDs and symbols as inputs by adding asset locations
closes: [#405](https://github.com/paritytech/asset-transfer-api/issues/405)
=> fix: improve error messages

examples/assetHubToMoonriverPaysWithFeeOrigin.ts, examples/kusama/assetHub/paysWithFeeOriginTransfers/usdtToMoonriverPaysWithUSDT.ts, examples/polkadot/assetHub/paysWithFeeOriginTransfers/dotToHydrationPaysWithGLMR.ts, examples/rococo/assetHub/paysWithFeeOriginTransfers/rocToBasiliskPaysWithMUSE.ts, src/AssetTransferApi.spec.ts, src/AssetTransferApi.ts, src/createXcmTypes/util/getPaysWithFeeOriginAssetLocationFromRegistry.spec.ts, src/createXcmTypes/util/getPaysWithFeeOriginAssetLocationFromRegistry.ts, src/integrationTests/AssetsTransferApi.spec.ts
This PR removes legacy functionality which allowed for `sufficient assets` to be used with the `paysWithFeeOrigin` option. Now only valid asset locations, symbols or integer IDs are able to be passed into `paysWithFeeOrigin`. Non unique and invalid values will throw an error.
* added ability to provide asset symbols (e.g. `usdt`) and asset integer IDs (e.g. `1984`) as values to `paysWithFeeOrigin`. The asset location in these cases is derived by the API if valid.
closes: [#419](https://github.com/paritytech/asset-transfer-api/issues/419)
=> fix: Update `paysWithFeeOrigin` examples and errors

README.md, examples/fetchFeeInfo.ts, src/AssetTransferApi.spec.ts, src/AssetTransferApi.ts, src/integrationTests/parachains/bifrost.spec.ts, src/testHelpers/adjustedMockBifrostParachainApi.ts, src/testHelpers/adjustedMockMoonriverParachainApi.ts, src/testHelpers/adjustedMockSystemApiV1004000.ts, src/testHelpers/adjustedMockSystemApiV1016000.ts
Fixes a bug where an incorrect extrinsic argument to `queryInfo` caused the `partialFee` of the returned `RuntimeDispatchInfo` to always be 0.
example Bifrost Polkadot -> Polkadot AssetHub input:
```typescript
callInfo = await assetApi.createTransferTransaction(
'1000',
'0xc4db7bcb733e117c0b34ac96354b10d47e84a006b9e7e66a229d174e8ff2a063',
['WETH'],
['1000000000000000000'],
{
format: 'call',
xcmVersion: safeXcmVersion,
},
);
const feeInfo = await assetApi.fetchFeeInfo(callInfo.tx, 'call');
console.log(
`${PURPLE}The following feeInfo data that is returned:\n${GREEN}${JSON.stringify(feeInfo?.toHuman(), null, 4)}`,
);
```
expected output:
```
The following feeInfo data that is returned:
{
"weight": {
"refTime": "1,600,000,000",
"proofSize": "0"
},
"class": "Normal",
"partialFee": "83.0091 …
```
=> fix(bug): fix fetchFeeInfo partial fee

README.md, src/AssetTransferApi.spec.ts, src/AssetTransferApi.ts, src/config/disabledOpts.ts, src/createXcmCalls/util/establishXcmPallet.spec.ts, src/createXcmCalls/util/establishXcmPallet.ts, src/integrationTests/parachains/bifrost.spec.ts, src/integrationTests/parachains/moonriver.spec.ts, src/integrationTests/util.ts, src/testHelpers/adjustedMockBifrostParachainApi.ts, src/types.ts
This PR refactors existing pallet selection logic to default to palletXcm rather than the xTokens pallet when both are available in the runtime. It also adds an additional option to the `TransferArgsOpts` called `xcmPalletOverride` to allow users to manually select palletXcm or xTokens pallets to construct a tx.
=> fix: default to xcmPallet

examples/paraToParaTransferMultiAsset.ts, examples/paraToParaTransferMultiAssetWithFee.ts, examples/paraToParaTransferMultiAssets.ts, examples/paraToRelayTransferMultiAsset.ts, examples/paraToSystemTransferMultiAsset.ts, examples/paraToSystemTransferMultiAssetWithFee.ts, examples/paraToSystemTransferMultiAssets.ts, examples/polkadot/parachain/paysWithFeeDest/bifrostToAssetHubPaysWithDOT.ts, src/AssetTransferApi.spec.ts, src/createXcmCalls/polkadotXcm/transferAssets.ts, src/createXcmTypes/ParaToSystem.ts, src/errors/checkXcmTxInputs.spec.ts, src/errors/checkXcmTxInputs.ts, src/integrationTests/AssetsTransferApi.spec.ts, src/util/getFeeAssetItemIndex.ts, src/util/resolveMultiLocation.spec.ts, src/util/resolveMultiLocation.ts
This PR removes an XCM check which restricted the number of assets that could be provided when constructing a `transferAssets` extrinsic to 1. This allows for a second asset to be provided in the `assetIds` and `amounts` fields in order to be used with the `paysWithFeeDest` option for selecting a different asset to pay fees on the destination chain.
=> fix: enable paysWithFeeDest for transferAssets

package.json, yarn.lock
we import these PJS deps but they are transitive dependencies. they should be declared explictly in package.json. this will also allow dependabot to update them
=> chore: declare explicit pjs dependencies

.github/dependabot.yml
Solves the issues of having to manually change the PR title prefix opened by the Dependabot.
=> fix: dependabot PR title

yarn.lock
Reverts paritytech/asset-transfer-api#468
=> chore(deps): revert bump @substrate/asset-transfer-api-registry from 0.2.24 to 0.2.25"

src/integrationTests/AssetsTransferApi.spec.ts, src/util/resolveMultiLocation.ts
Added this very small check because otherwise with : 
- this `asset-transfer-api-registry` update - PR [#180](https://github.com/paritytech/asset-transfer-api-registry/pull/180)
- and for this case in `asset-transfer-api` - Issue [#544](https://github.com/paritytech/asset-transfer-api/issues/544)
This line of code throws an error because it always expects for `xcmVersion > 3` to have `X1` in `result.interior` which I do not think it is the case. This can be double checked by using for example : 
- https://polkadot.js.org/apps/#/runtime connected to Polimec chain
- `xcmPaymentApi` - `queryAcceptablePaymentAssets`
- xcmVersion : 4
- the result will give also assets that have `interior.X3` and some other that have `interior.X1`
=> fix: check if X1 exists in multilocation

e2e-tests/polkadotAssetHub.hydration.spec.ts, src/AssetTransferApi.ts, src/integrationTests/AssetsTransferApi.spec.ts, yarn.lock
`dryRun` calls require an `xcmVersion`. Default to `safeXcm` version if none is given.
Relates to [this comment in polkadot-sdk](https://github.com/paritytech/polkadot-sdk/pull/7438/files#r2113620849).
Also fixes the test issue mentioned in these PRs:
- https://github.com/paritytech/asset-transfer-api/pull/568
- https://github.com/paritytech/asset-transfer-api/pull/567
- https://github.com/paritytech/asset-transfer-api/pull/566
=> fix: dryRun requires xcmVersion, so use safeXcmVersion if none given

src/registry/registry-json.ts
fixes https://github.com/paritytech/asset-transfer-api/issues/570
=> fix: replace `assert` with `with` to support newer node versions

src/AssetTransferApi.spec.ts, src/AssetTransferApi.ts
The readability of function calls with 5+ arguments really suffers. It is too easy to mix up destination and origin or `isForeignAssetsTransfer` and `isParachainPrimaryNativeAsset`. Moving to object params for these, makes everything a little more explicit and readable.
No public functions were changed.
AssetTransferApi private methods that were changed:
- `constructFormat`
- `fetchCallType`
- `createLocalTx`
- `resolveCall`
=> refactor: Move to oject params for private methods with many arguments

src/AssetTransferApi.spec.ts, src/AssetTransferApi.ts
It was redundant with assetType which is either Native or Foreign.
=> refactor: Remove isForeignAssetsTransfer from `fetchCallType`

e2e-tests/astar.spec.ts, src/createXcmCalls/polkadotXcm/transferAssetsUsingTypeAndThen.ts, src/createXcmTypes/types.ts
I noticed room for improvement while debugging unrelated issues.
Effectively lean more heavily on `xcmCreator` instead of casting and implementing xcmVersion specific logic elsewhere.
=> refactor: transferAssetsUsingTypeAndThenCleanup

src/AssetTransferApi.ts, src/createXcmCalls/polkadotXcm/claimAssets.spec.ts, src/createXcmCalls/polkadotXcm/claimAssets.ts, src/createXcmTypes/util/createAssetLocations.ts
This is in place of treating all assets as the same if a single one contains a multilocation.
Also used this as an opportunity to move `claimAssets()` to object params as well as remove `CreateXcmCallOpts` parameter from `claimAssets()` as it was out of place.
=> fix: Check assets individually in `claimAssets(...)`
